# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.tabs.remote.autostart.2", false);
user_pref("browser.startup.homepage", "https://www.google.com/");
user_pref("browser.startup.page", 0);
